@startmindmap
'https://plantuml.com/mindmap-diagram

skinparam wrapwidth 200

* мотивация
** это - побуждение к действию
*** локус
**** внешняя
**** внутренняя
*** модальность
**** положительная
**** отрицательная
*** повторяемость
**** индивидуальная
**** групповая
** конкурирующие программы
*** мотивов много
*** человек - один
left side

**[#coral] отраслевые особенности труда
***[#coral] параметры работы = стрессогенные факторы
****[#coral] регулярная активная коммуникация
****[#coral] жесткие сроки выполнения задач
****[#coral] многозадачность
****[#coral] постоянные изменения
****[#coral] высокий темп работы
****[#coral] большой объем рабочей информации
***[#coral] стресс = сильное эмоциональное или физическое напряжение
**[#gold] законы Йеркса-Додсона
***[#gold] в 1908 году ученые Роберт Йеркс и Джон Диллингем Додсон проводили эксперимент: они наблюадали за передвижением крыс в лабиринте. Животные при этом подвергались ударам электрического тока. Ученые установили, что сначала, при увеличении силы тока, крысы бежали по лабиринту с большей скоростью, но при очередном повышении силы импульсов крысы начали хаотично передвигаться по лабиринту. Время прохождения препятствия увеличилось.
**** <img:/zakon_1.jpg{scale=0.3}>
**** <img:/zakon_2.jpg{scale=0.3}>
***[#gold] Экспериментально было определено, что для простых задач оптимальной является мотивация 5-6 баллов по 7-балльной шкале, для задач средней сложности – около 4, для трудных заданий – 1-2 балла.
**[#lime] практика применения
***[#lime] для простых задач увличиваем мотивацию (сложность, значимость)
***[#lime] для сложных задач ее снижаем (декомпозиция, больше времени, презумпция добросовестности, ограниченность применимости решения во времени)
***[#lime] "капсулы" Евгения Идзиковского


@endmindmap
