@startmindmap
'https://plantuml.com/mindmap-diagram
top to bottom direction
skinparam wrapWidth 200
skinparam align center



* **1908**
** <img:/zakon_1.jpg{scale=0.6}>

** <img:/Йеркс.png{scale=0.5}>
*** Роберт Мирнс Йеркс (1876-1956)
**** <img:/dodson.jpeg{scale=0.42}>
***** Джон Диллингем Додсон (1879-1955)
** <img:/zakon_2.jpg{scale=0.6}>





@endmindmap
