@startmindmap
'https://plantuml.com/mindmap-diagram
top to bottom direction
skinparam wrapWidth 200
skinparam defaulttextalignment center
* **задача**
**[#lime] идёт
**[#red] не идёт
*** сложная
**** значительно превышает уровень навыков
***** вызывает тревогу, страх
'*** простая
'**** ниже уровня навыков
'***** скука

@endmindmap
