@startuml
'https://plantuml.com/activity-diagram-beta
skinparam wrapWidth 480
skinparam defaulttextalignment left

start
:задача;
if (задача идет ?) is (да) then
 #lime :  выполняем задачу;
  stop
else (нет)
  :оценить сложность задачи;
  if (сложность задачи превышает навыки?) is (да) then
  #hotpink  :задача сложная;
 switch (  )
  case (снижение стресса )
    : **План А**
    * сфокусироваться на задаче
    * донести до команды информацию о сложности задачи
    * попросить помощи;
  case ( снижение сложности )
    : **План Б**
    * уточнить ожидания
    * декомпозировать задачу
    * использовать шаблонные решения;

  endswitch

 else (нет)
   #skyblue :задача простая;
   :**повышение сложности**
   * решаем при помощи новых инструментов/технологий
   * ограничиваем срок выполнения
   * отдаем джуну и обучаем его
   * просим своего ментора о ревью задачи;
  endif
endif
 #lime :  выполняем задачу;

stop

@enduml
